---
server:
  port: 9200
management:
  server:
    port: 9201
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      hibernate:
        stat: INFO
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
        orm:
          jdbc:
            bind: INFO
spring:
  security:
    api-key: xxx
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
    show-sql: true
  datasource:
    url: "jdbc:mariadb://rp-register-db:3306/rp_register_db"
    driver-class-name: org.mariadb.jdbc.Driver
    username: eudiw_user
    password: lesssecret
    hikari:
      connection-timeout: 3000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 1 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 1 #maximum pool size
      idle-timeout: 1000 #maximum idle time for connection
      max-lifetime: 500 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
  application:
    environment: docker

eudiw-rp-register-service:
  csr-service:
    ca-service-api:
      ca-service-base-uri: http://ca-service:9220
      api-key-value: eudiw

external-dependency-health-checks:
  enabled: false
