---
server:
  port: 9200

spring:
  thread-executor: virtual
  security:
    include-paths:
      - /v1/**
    exclude-paths:
      - /
      - /health/**
      - /version
      - /info
      - /prometheus
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs/**
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  flyway:
    table: flyway_schema_history
  application:
    name: eudiw-rp-register-service
    environment: default

  jackson:
    deserialization:
      # reject API resources with unknown/extra fields in them
      fail-on-unknown-properties: true

# Spring Boot Actuator
management:
  server:
    port: 9201
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,version,prometheus,health
  endpoint:
    health:
      group:
        readiness:
          include: db
        liveness:
          include: livenessState
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

digdir:
  audit:
    application-name: ${spring.application.name}
    application-environment: ${spring.application.environment}
    audit-log-dir:
    filters:
      bearer-token: false
  event:
    logging:
      environment-name: ${spring.application.environment}

eudiw-rp-register-service:
  csr-service:
    ca-service-api:
      api-key-header-id: X-API-KEY
      ca-service-base-uri: http://eudiw-ca-service-service:8080
    rest-client:
      connect-timeout-millis: 5000
      read-timeout-millis: 5000

---
spring:
  config:
    activate:
      on-cloud-platform: 'kubernetes'
    import:
      - 'optional:file:/etc/config/'
