---
server:
  port: 9200
management:
  server:
    port: 9201
  endpoint:
    health:
      show-details: always
spring:
  security:
    api-key: xxx
  datasource:
    url: "jdbc:h2:mem:eudiw_user;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    environment: local-h2

eudiw-rp-register-service:
  csr-service:
    ca-service-api:
      ca-service-base-uri: http://ca-service:9220
      api-key-value: eudiw

external-dependency-health-checks:
  enabled: false
