---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: digital-lommebok-trustlist-service
    environment: default

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

trustlist-service:
  environment-name: ${spring.application.environment}
  digdir:
    name-no: Digitaliseringsdirektoratet
    name-en: Digitaliseringsdirektoratet
    email: mailto:servicedesk@digdir.no
    web: https://www.digdir.no/
    postal-address:
      street-address: Lørenfaret 1C
      postal-code: 0580
      locality: Oslo
      country: "NO"
  tsl612:
    trustlist-path: /no_eidas2sandkasse_${trustlist-service.environment-name}_tsl
    trustlist-path-xtsl: ${trustlist-service.tsl612.trustlist-path}.xtsl
    trustlist-path-sha2: ${trustlist-service.tsl612.trustlist-path}.sha2
    keystore: signing-612
    scheme-information:
      scheme-name:
        lang-no: Tillitsliste for norsk eidas2sandkasse i ${trustlist-service.environment-name}
        lang-en: Trust list for eidas2sandkasse in ${trustlist-service.environment-name}
      sequence-number: 1
      list-issue-datetime: 2026-02-27T00:00:00.00Z
    # only support 1 trust service provider initially
    service-provider:
      name:
        lang-no: Digitaliseringsdirektoratet
        lang-en: Norwegian Digitalisation Agency
      trade-name:
        lang-no: NTRNO-991825827
        lang-en: NTRNO-991825827
      information-uri:
        lang-no: https://docs.digdir.no/docs/lommebok/lommebok_om.html

  tsl-aca:
    path: /no_eidas2sandkasse_${trustlist-service.environment-name}_aca
    keystore: signing-602
    scheme-information:
      scheme-name:
        lang-no: NO:Tillitsliste for Access Certificate Authorities i eidas2sandkasse i ${trustlist-service.environment-name}
        lang-en: NO:Trust list for Access Certificate Authorities in eidas2sandkasse in ${trustlist-service.environment-name}
      sequence-number: 1
      list-issue-datetime: 2026-02-27T00:00:00.00Z

    trusted-entities:
      - trusted-entity-information:
          information-uri:
            a: https://docs.digdir.no/docs/lommebok/lommebok_om.html
            c: http://uri.etsi.org/19602/ListOfTrustedEntities/WRPACProvider/NO
        trusted-entity-services:
          - service-information:
              service-name:
                lang-no: CA for relying parties access certificates in eidas2sandkasse
                lang-en: CA for relying parties access certificates in eidas2sandkasse
              service-digital-identity:
                cert: cert


idporten-key-manager:
  default-keystore: signing-612  # Optional, first keystore becomes default if not specified
  keystores:
    signing-612:
      key-store-location: ${TSL_612_SIGN_KEYSTORE}
      key-store-type: ${TSL_612_SIGN_KEYSTORE_TYPE}
      key-store-password: ${TSL_612_SIGN_KEYSTORE_KEY_PASSWORD}
      key-alias: ${TSL_612_SIGN_KEYSTORE_KEY_ALIAS}
      key-password: ${TSL_612_SIGN_KEYSTORE_KEY_PASSWORD}
    signing-602:
      key-store-location: ${TSL_602_SIGN_KEYSTORE}
      key-store-type: ${TSL_602_SIGN_KEYSTORE_TYPE}
      key-store-password: ${TSL_602_SIGN_KEYSTORE_KEY_PASSWORD}
      key-alias: ${TSL_602_SIGN_KEYSTORE_KEY_ALIAS}
      key-password: ${TSL_602_SIGN_KEYSTORE_KEY_PASSWORD}
