---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: eudiw-trust-list-service
    environment: default

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

trust-service:
  keystore:
    type: ${TSL_SIGN_KEYSTORE_TYPE}
    location: ${TSL_SIGN_KEYSTORE}
    password: ${TSL_SIGN_KEYSTORE_KEY_PASSWORD}
    key-alias: ${TSL_SIGN_KEYSTORE_KEY_ALIAS}
    key-password: ${TSL_SIGN_KEYSTORE_KEY_PASSWORD}
