name: eudiw-rp-register
networks:
  eudiw:
    name: eudiw

services:
  rp-register-db:
    image: "mariadb:11.4"
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_DATABASE: register_service
      MARIADB_USER: eudiw_user
      MARIADB_PASSWORD: lesssecret
    ports:
      - "36306:3306"
    networks:
      - eudiw
    healthcheck:
      test: mysqladmin -p$$MARIADB_ROOT_PASSWORD -uroot ping -h localhost
      interval: 5s
      start_period: 5s
      timeout: 5s
      retries: 10

  rp-register-service:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    environment:
      spring_profiles_active: docker
      _JAVA_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:UseSVE=0"
    ports:
      - "7080:7080"
    networks:
      - eudiw
    depends_on:
      rp-register-db:
        condition: service_healthy
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/webapps
        java -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7080/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20
