---
server:
  port: 9294

spring:
  config:
    import: optional:file:${EUDIW_CREDENTIAL_REGISTRY_ENV}[.properties]
  application:
    environment: docker


# Spring Boot Actuator
management:
  server:
    port: 9294


credential-registry:
  rp-register-service-url: http://rp-register-service:9200/v1/credential-issuers
  api-key-header-id: X-API-KEY
  api-key-value: ${REGISTER_SERVICE_API_KEY}
