---
spring:
  application:
    environment: test

eudiw-ca:
  base-uri: "https://ca.test.eidas2sandkasse.net"
  roots:
    root:
      root: root
      lifetime-days: 1825
      crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/root.crl
      certificate-uri: ${eudiw-ca.base-uri}/v1/certs/root.cer
      keystore:
        type: pkcs12
        location: ${ROOT_KEYSTORE_LOCATION}
        password: ${ROOT_KEYSTORE_PASSWORD}
        key-alias: ${ROOT_KEYSTORE_KEY_ALIAS}
        key-password: ${ROOT_KEYSTORE_KEY_PASSWORD}
  intermediates:
    access:
      root: root
      lifetime-days: 100
      crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/intermediates/access.crl
      certificate-uri: ${eudiw-ca.base-uri}/v1/certs/intermediates/access.cer
      certificate-profile:
        extended-key-usage:
          - "1.0.18013.5.1.6"
      keystore:
        type: pkcs12
        location: ${INTERMEDIATE_ACCESS_KEYSTORE_LOCATION}
        password: ${INTERMEDIATE_ACCESS_KEYSTORE_PASSWORD}
        key-alias: ${INTERMEDIATE_ACCESS_KEYSTORE_KEY_ALIAS}
        key-password: ${INTERMEDIATE_ACCESS_KEYSTORE_KEY_PASSWORD}
    pid_provider:
      root: root
      lifetime-days: 365
      crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/intermediates/pid_provider.crl
      certificate-uri: ${eudiw-ca.base-uri}/v1/certs/intermediates/pid_provider.cer
      #      certificate-profile:
      #        qc-statements:
      #          qc-type: id-etsi-qct-pid
      keystore:
        type: pkcs12
        location: ${INTERMEDIATE_PID_PROVIDER_KEYSTORE_LOCATION}
        password: ${INTERMEDIATE_PID_PROVIDER_KEYSTORE_PASSWORD}
        key-alias: ${INTERMEDIATE_PID_PROVIDER_KEYSTORE_KEY_ALIAS}
        key-password: ${INTERMEDIATE_PID_PROVIDER_KEYSTORE_KEY_PASSWORD}
    eaa_provider:
      root: root
      lifetime-days: 365
      crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/intermediates/eaa_provider.crl
      certificate-uri: ${eudiw-ca.base-uri}/v1/certs/intermediates/eaa_provider.cer
      keystore:
        type: pkcs12
        location: ${INTERMEDIATE_EAA_PROVIDER_KEYSTORE_LOCATION}
        password: ${INTERMEDIATE_EAA_PROVIDER_KEYSTORE_PASSWORD}
        key-alias: ${INTERMEDIATE_EAA_PROVIDER_KEYSTORE_KEY_ALIAS}
        key-password: ${INTERMEDIATE_EAA_PROVIDER_KEYSTORE_KEY_PASSWORD}
