---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: eudiw-ca-service
    environment: default
  security:
    api-key: ${API_KEY}
    include-paths:
      - /v1/certs/access
    exclude-paths:
      - /
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs/**
      - /v1/certs/root**
      - /v1/certs/intermediates/**
      - /info
      - /health**
      - /health/**
      - /version
      - /prometheus
# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true

eudiw-ca:
  base-uri: "http://eudiw-ca-service:9220"
  root:
    root: true
    lifetime-days: 1825
    crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/root.crl
    certificate-uri: ${eudiw-ca.base-uri}/v1/certs/root.crt
    keystore:
      type: pkcs12
      location: ${ROOT_KEYSTORE_LOCATION}
      password: ${ROOT_KEYSTORE_PASSWORD}
      key-alias: ${ROOT_KEYSTORE_KEY_ALIAS}
      key-password: ${ROOT_KEYSTORE_KEY_PASSWORD}
  intermediates:
    access:
      lifetime-days: 100
      crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/intermediates/access.crl
      certificate-uri: ${eudiw-ca.base-uri}/v1/certs/intermediates/access.crt
      keystore:
        type: pkcs12
        location: ${INTERMEDIATE_ACCESS_KEYSTORE_LOCATION}
        password: ${INTERMEDIATE_ACCESS_KEYSTORE_PASSWORD}
        key-alias: ${INTERMEDIATE_ACCESS_KEYSTORE_KEY_ALIAS}
        key-password: ${INTERMEDIATE_ACCESS_KEYSTORE_KEY_PASSWORD}
    issuer:
      lifetime-days: 100
      crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/intermediates/issuer.crl
      certificate-uri: ${eudiw-ca.base-uri}/v1/certs/intermediates/issuer.crt
      keystore:
        type: pkcs12
        location: ${INTERMEDIATE_ISSUER_KEYSTORE_LOCATION}
        password: ${INTERMEDIATE_ISSUER_KEYSTORE_PASSWORD}
        key-alias: ${INTERMEDIATE_ISSUER_KEYSTORE_KEY_ALIAS}
        key-password: ${INTERMEDIATE_ISSUER_KEYSTORE_KEY_PASSWORD}
