---
server:
  port: 9220

management:
  server:
    port: 9221
  endpoint:
    health:
      show-details: always

spring:
  application:
    environment: docker
  datasource:
    url: "jdbc:mariadb://ca-db:3306/ca_db"

eudiw-ca:
  base-uri: "http://ca-service:9220"
