---
spring:
  thread-executor: virtual
  application:
    name: eudiw-rp-ca-service
    environment: default

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8080

