---
server:
  port: 9220

management:
  server:
    port: 9221

spring:
  config:
    import: file:.env[.properties]
  application:
    environment: dev

eudiw-ca:
  base-uri: "http://eudiw-ca-service:9220"
