---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: eudiw-ca-service
    environment: default
  security:
    api-key: ${API_KEY}
    include-paths:
      - /v1/certs/access
    exclude-paths:
      - /
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs/**
      - /v1/certs/root**
      - /v1/certs/intermediates/**
      - /info
      - /health**
      - /health/**
      - /version
      - /prometheus
  datasource:
    url: url-in-env-profile
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 3000
      minimum-idle: 1
      maximum-pool-size: 1
      idle-timeout: 1000
      max-lifetime: 500
  flyway:
    table: flyway_schema_history
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

eudiw-ca:
  base-uri: "http://eudiw-ca-service:9220"
  root:
    root: true
    lifetime-days: 1825
    crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/root.crl
    certificate-uri: ${eudiw-ca.base-uri}/v1/certs/root.cer
    keystore:
      type: pkcs12
      location: ${ROOT_KEYSTORE_LOCATION}
      password: ${ROOT_KEYSTORE_PASSWORD}
      key-alias: ${ROOT_KEYSTORE_KEY_ALIAS}
      key-password: ${ROOT_KEYSTORE_KEY_PASSWORD}
  intermediates:
    access:
      lifetime-days: 100
      crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/intermediates/access.crl
      certificate-uri: ${eudiw-ca.base-uri}/v1/certs/intermediates/access.cer
      certificate-profile:
        extended-key-usage:
          - "1.0.18013.5.1.6"
      keystore:
        type: pkcs12
        location: ${INTERMEDIATE_ACCESS_KEYSTORE_LOCATION}
        password: ${INTERMEDIATE_ACCESS_KEYSTORE_PASSWORD}
        key-alias: ${INTERMEDIATE_ACCESS_KEYSTORE_KEY_ALIAS}
        key-password: ${INTERMEDIATE_ACCESS_KEYSTORE_KEY_PASSWORD}
    issuer:
      lifetime-days: 100
      crl-distribution-point: ${eudiw-ca.base-uri}/v1/certs/intermediates/issuer.crl
      certificate-uri: ${eudiw-ca.base-uri}/v1/certs/intermediates/issuer.cer
      keystore:
        type: pkcs12
        location: ${INTERMEDIATE_ISSUER_KEYSTORE_LOCATION}
        password: ${INTERMEDIATE_ISSUER_KEYSTORE_PASSWORD}
        key-alias: ${INTERMEDIATE_ISSUER_KEYSTORE_KEY_ALIAS}
        key-password: ${INTERMEDIATE_ISSUER_KEYSTORE_KEY_PASSWORD}
