name: eudiw-rp-register
networks:
  eudiw:
    name: eudiw

services:
  rp-register-admin:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    environment:
      spring_profiles_active: docker
      _JAVA_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:UseSVE=0"
    env_file:
      - .env
    ports:
      - "9250:9250"
      - "9251:9251"
      - "9255:9255"
    networks:
      - eudiw
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/tomcat/webapps/
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9255 -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9251/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20
