name: digital-lommebok-rp
networks:
  digital-lommebok:
    name: digital-lommebok

services:
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      start_period: 3s
      timeout: 2s
      retries: 20
    ports:
      - "6370:6379"
    networks:
      - digital-lommebok
    command: redis-server --maxmemory-policy allkeys-lru
  rp-register-db:
    image: "mariadb:11.4"
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_DATABASE: rp_register_db
      MARIADB_USER: eudiw_user
      MARIADB_PASSWORD: lesssecret
    ports:
      - "36306:3306"
    networks:
      - digital-lommebok
    healthcheck:
      test: mariadb-admin -p$$MARIADB_ROOT_PASSWORD -uroot ping -h localhost
      interval: 5s
      start_period: 5s
      timeout: 5s
      retries: 10

  rp-register-service:
    build:
      context: ../..
      dockerfile: apps/eudiw-rp-register-service/docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    env_file:
      - ${EUDIW_RP_REGISTER_SERVICE_ENV}
    environment:
      spring_profiles_active: docker
    ports:
      - "9200:9200"
      - "9201:9201"
      - "9205:9205"
    networks:
      - digital-lommebok
    depends_on:
      rp-register-db:
        condition: service_healthy
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/webapps
        java -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9201/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20
  rp-register-admin:
    build:
      context: ../..
      dockerfile: apps/eudiw-rp-register-admin/docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    env_file:
      - ${EUDIW_RP_REGISTER_ADMIN_ENV}
    environment:
      spring_profiles_active: docker, admin, admin-docker
    ports:
      - "9250:9250"
      - "9251:9251"
      - "9252:9252"
    networks:
      - digital-lommebok
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/webapps/
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9251 -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9250/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20
  rp-register-selfservice:
    build:
      context: ../..
      dockerfile: apps/eudiw-rp-register-admin/docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    env_file:
      - ${EUDIW_RP_REGISTER_ADMIN_ENV}
    environment:
      spring_profiles_active: docker, selfservice, selfservice-docker
    ports:
      - "9255:9255"
      - "9256:9256"
    networks:
      - digital-lommebok
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/webapps/
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9256 -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9255/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20

  rp-register-lookup-web:
    build:
      context: ../..
      dockerfile: apps/eudiw-rp-register-lookup-web/docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    env_file:
      - ${EUDIW_RP_REGISTER_LOOKUP_WEB_ENV}
    environment:
      spring_profiles_active: docker
    ports:
      - "9210:9210"
      - "9211:9211"
      - "9215:9215"
    networks:
      - digital-lommebok
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/webapps/
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9215 -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9211/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20

  ca-db:
    image: "mariadb:11.4"
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
      MARIADB_DATABASE: ca_db
      MARIADB_USER: ca
      MARIADB_PASSWORD: ca
    ports:
      - "9226:3306"
    networks:
      - digital-lommebok
    healthcheck:
      test: mariadb-admin -p$$MARIADB_ROOT_PASSWORD -uroot ping -h localhost
      interval: 5s
      start_period: 5s
      timeout: 5s
      retries: 10
  ca-service:
    extends:
      file: ../eudiw-ca-service/docker-compose.yaml
      service: ca-service

  credential-registry:
    extends:
      file: ../eudiw-credential-registry/docker-compose.yaml
      service: credential-registry

  trustlist-service:
    build:
      context: ../..
      dockerfile: apps/eudiw-trustlist-service/docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    environment:
      spring_profiles_active: docker
      _JAVA_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:UseSVE=0"
    env_file:
      - ${EUDIW_TRUSTLIST_SERVICE_ENV}
    ports:
      - "9230:9230"
      - "9235:9235"
    networks:
      - digital-lommebok
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/webapps/
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9235 -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9230/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20
