---
server:
  port: 9210

management:
  server:
    port: 9211
  endpoint:
    health:
      show-details: always
      
eudiw-rp-register-lookup-web:
  service:
    rest-client-defaults:
      register-service-api-base-uri: http://rp-register-service:9200/v1/rp
      api-key-value: xxx

spring:
  application:
    environment: docker

external-dependency-health-checks:
  enabled: false
