---
server:
  port: 9210

management:
  server:
    port: 9211
  endpoint:
    health:
      show-details: always

spring:
  application:
    environment: docker

external-dependency-health-checks:
  enabled: false