---
server:
  port: 9210

management:
  server:
    port: 9211
  endpoint:
    health:
      show-details: always

eudiw-rp-register-lookup-web:
  relying-parties-service:
    register-service-api:
      register-service-base-uri: http://digital-lommebok-rp-register-service-service:9200
  credentials-service:
    credentials-registry-api:
      credentials-registry-base-uri: http://credential-register:9294

spring:
  application:
    environment: dev

external-dependency-health-checks:
  enabled: false
