---
server:
  port: 8080

  servlet:
    session:
      tracking-modes: cookie

spring:
  thread-executor: virtual
  application:
    name: eudiw-rp-register-lookup-web
    environment: default


# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true

eudiw-rp-register-lookup-web:
  service:
    api-search-endpoint: /search
    rest-client-defaults:
      register-service-api-base-uri: ${API_BASE_URI}
      api-key-header-id: X-API-KEY
      api-key-value: ${API_KEY_VALUE}
      connect-timeout-millis: 5000
      read-timeout-millis: 5000
