---
server:
  port: 9250

management:
  server:
    port: 9251

spring:
  application:
    environment: docker

external-dependency-health-checks:
  enabled: false

eudiw-admin-web:
  relying-parties-service:
    register-service-api:
      register-service-base-uri: http://rp-register-service:9200
      api-key-value: xxx
