---
spring:
  security:
    oauth2:
      client:
        registration:
          ansattporten:
            client-id: ${ANSATTPORTEN_CLIENT_ID}
            client-secret: ${ANSATTPORTEN_CLIENT_SECRET}
            provider: ansattporten
            client-name: Logg inn via Ansattporten
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
        provider:
          ansattporten:
            issuer-uri: https://ansattporten.dev
