---
spring:
  application:
    environment: systest

eudiw-admin-web:
  security:
    ansattporten:
      allow-synthetic-reportee: true
      allow-entra-id: true
      entra-id-request-authorization-details:
        - type: ansattporten:orgno
