---
spring:
  application:
    environment: systest

eudiw-admin-web:
  enhetsregisteret-service:
    enhetsregisteret-api-base-uri: "https://data.ppe.brreg.no/enhetsregisteret/api/enheter"
  security:
    ansattporten:
      allow-synthetic-reportee: true
      allow-entra-id: true
      entra-id-request-authorization-details:
        - type: ansattporten:orgno
