---
spring:
  application:
    environment: docker

external-dependency-health-checks:
  enabled: false

eudiw-admin-web:
  relying-parties-service:
    register-service-api:
      register-service-base-uri: http://rp-register-service:9200
      api-key-value: xxx
  security:
    ansattporten:
      allow-synthetic-reportee: true
      request-authorization-details:
        - type: ansattporten:altinn:resource
          resource: urn:altinn:resource:digdir-selvbetjening-klienter
        - type: ansattporten:altinn:resource
          resource: urn:altinn:resource:digdir-selvbetjening-api-maskinporten
        - type: ansattporten:altinn:resource
          resource: urn:altinn:resource:digdir-selvbetjening-leverandorer
        - type: ansattporten:altinn:resource
          resource: urn:altinn:resource:digdir-selvbetjening-samarbeid-testmiljo
      allow-entra-id: true
      entra-id-request-authorization-details:
        - type: ansattporten:orgno
