---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: eudiw-rp-register-admin
    environment: default

management:
  server:
    port: 8090
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,version,prometheus,health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
      status:
        order: DOWN, OUT_OF_SERVICE, UNKNOWN, DEGRADED, EXTERNAL_DEPENDENCY_DOWN, UP
  health:
    group:
      readiness:
        include: db
      liveness:
        include: livenessState

eudiw-admin-web:
  service:
    rest-client:
      register-service-api-base-uri: ${API_BASE_URI}
      api-key-header-id: X-API-KEY
      api-key-value: ${API_KEY_VALUE}
      connect-timeout-millis: 5000
      read-timeout-millis: 5000

external-dependency-health-checks:
  health-endpoints:
    eudiw-rp-service:
      name: eudiw-rp-service
      base-uri: http://eudiw-rp-service-service:8090
      endpoint: /health
      connect-timeout-ms: 2000
      read-timeout-ms: 1000
      map-down-status-to: DOWN
