name: eudiw-rp-register
networks:
  eudiw:
    name: eudiw

services:
  rp-ca-service:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    environment:
      spring_profiles_active: docker
      _JAVA_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:UseSVE=0"
    ports:
      - "9220:9220"
      - "9221:9221"
      - "9225:9225"
    networks:
      - eudiw
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/tomcat/webapps/
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9225 -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9211/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20
