name: digital-lommebok-rp
networks:
  digital-lommebok:
    name: digital-lommebok

services:
  ca-db:
    image: "mariadb:11.4"
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
      MARIADB_DATABASE: ca_db
      MARIADB_USER: ca
      MARIADB_PASSWORD: ca
    ports:
      - "9226:3306"
    networks:
      - digital-lommebok
    healthcheck:
      test: mariadb-admin -p$$MARIADB_ROOT_PASSWORD -uroot ping -h localhost
      interval: 5s
      start_period: 5s
      timeout: 5s
      retries: 10
  ca-service:
    depends_on:
      ca-db:
        condition: service_healthy
    build:
      context: ../..
      dockerfile: apps/eudiw-ca-service/docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    environment:
      spring_profiles_active: docker
      _JAVA_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:UseSVE=0"
    env_file:
      - ${EUDIW_CA_SERVICE_ENV}
    ports:
      - "9220:9220"
      - "9221:9221"
      - "9225:9225"
    networks:
      - digital-lommebok
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/tomcat/webapps/
        java -javaagent:opentelemetry-javaagent.jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9225 -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9221/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20
